<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\chrome-logo.png" />
    <Resource Include="Assets\discord-logo.png" />
    <Resource Include="Assets\edge-logo.png" />
    <Resource Include="Assets\icon128.png" />
    <Resource Include="Assets\outlook-logo.png" />
    <Resource Include="Assets\slack-logo.png" />
    <Resource Include="Assets\teams-logo.png" />
    <Resource Include="Assets\whatsapp-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KungFlow.Desktop.Agent\KungFlow.Desktop.Agent.csproj" />
  </ItemGroup>

</Project>
